[[pages]]
path = "Welcome.py"
name = "Welcome"
icon = "ğŸ‘‹"

[[pages]]
path = "pages/About.py"
name = "About"
icon = "â„¹ï¸"

[[pages]]
name = "AML"
icon = ""
is_section = true

[[pages]]
path = "pages/AML_Suggestor.py"
name = "AML Suggestor"
icon = "ğŸ”®"

[[pages]]
path = "pages/AML_Identifier.py"
name = "AML Identifier"
icon = "ğŸ”"

[[pages]]
name = "Perspectives"
icon = ""
in_section = false
is_section = true

[[pages]]
path = "pages/Points_Of_View.py"
name = "Points of View"
icon = "ğŸ‘ï¸â€ğŸ—¨ï¸"

[[pages]]
path = "pages/Relative_Opinions.py"
name = "Relative Opinions"
icon = "ğŸ¤"

[[pages]]
path = "pages/Philosophers_Views.py"
name = "Philosophers Views"
icon = "ğŸ”­"

[[pages]]
path = "pages/Give_Us_Feedback.py"
name = "Give Us Feedback"
icon = "âœï¸"
in_section = false